### ISSUE TITLE
Enable container logs and support failure on setup/startup scripts errors

### ISSUE THREAD

**Issue by iamazeem** [gvenzl/setup-oracle-free#6]
Hi,

Thank you for your work on this container and this action! :+1: 

Apparently, there's no way to check if the setup/startup scripts fail.
Also, there's nothing on the stdout/stderr under the container run group in the logs.

Currently, I'm using it like this and checking for errors in a subsequent step:

```yml
- name: Setup Oracle container
  uses: gvenzl/setup-oracle-free@v1
  with:
    container-runtime: docker
    app-user: app_user
    app-user-password: app_user_password
    setup-scripts: ${{ github.workspace }}/scripts

- name: Check Oracle container logs for errors
  run: |
    docker container ls
    docker container logs oracledb | tee -a /tmp/oracledb.log
    if grep 'ERROR' /tmp/oracledb.log >/dev/null; then
      echo "[ERR] Something went wrong!"
      echo "[ERR] See above logs for more details."
      exit 1
    fi
```

Would it be possible to provide some input parameter to enable these logs e.g. `enable-logs`?
Also, something like `fail-on-setup-errors` and/or `fail-on-startup-errors` may be added.

What do you think?
LMK if you need any help from side.

Thanks and regards!
